# Production Docker Compose
version: '3.8'

services:
  webp-cli:
    image: public.ecr.aws/d8n6n6f3/cli:latest
    container_name: webp-cli
    env_file:
      - .env
    environment:
      # Ensure AWS credentials are properly set from .env
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      # Disable AWS profile lookup to force using env vars
      - AWS_PROFILE=
      - AWS_CONFIG_FILE=
      - AWS_SHARED_CREDENTIALS_FILE=
    volumes:
      # Mount logs directory for persistent logging
      - ./logs:/app/logs
    restart: "no"  # CLI should not restart automatically
    networks:
      - webp-network

networks:
  webp-network:
    driver: bridge